apiVersion: v1
kind: Pod
metadata:
  name: intellij

spec:
  restartPolicy: Never

  volumes:
  - name: ssh-key
    secret:
      secretName: private-keys

  containers:
  - name: intellij
    image: akop/intellij-ssh
    env:
    - name: USER
      value: {SSH-USER}
    - name: HOST
      value: {SSH-HOST}
    - name: PORT
      value: {SSH-PORT}
    volumeMounts:
    - name: ssh-key
      readOnly: true
      mountPath: "/private-keys"
